version: '3.3'

services:
    postgres:
      build:
        context: setup_db
        dockerfile: .
      ports:
        - "5432:5432"

    web:
      build:
        context: ./webpage
      ports:
        - "5000:5000"
